name: Build and publish dev-release Java distributions to sonatype.

on:
  push:
    branches:
      - dev-version-*
    paths:
      - gradle.properties

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java.yml@main
    with:
      build-target: 'Docker'
      docker-username: ${{ github.actor }}
      runsOn: ubuntu-latest
      devRelease: true
    secrets:
      docker-password: ${{ secrets.GITHUB_TOKEN }}