name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches:
      - master
      - version-*
    paths:
      - gradle.properties
#    - package_info.json  

jobs:
  build-job:
    uses: th2-net/.github/.github/workflows/compound-java.yml@th2-4135-trivy-workflow
    with:
      build-target: 'Docker'
      docker-username: ${{ github.repository_owner }}
    secrets:
      docker-password: ${{ secrets.CR_PAT }}
